In [1]:
import pandas as pd
import numpy as np
import os
from parts import data_holder as dh
from parts import prob_calculator as pc
from parts import discretizatior
from parts import trainer

In [2]:
DATA_DIR_PATH = os.path.join(os.getcwd(), "data")
DATA_SET_NAME = "sample.csv"
DATA_SET_PATH = os.path.join(DATA_DIR_PATH, DATA_SET_NAME)
DIVIDE_NUM = 5


In [3]:
base_df = pd.read_csv(DATA_SET_PATH, header=None)
class_set = base_df[base_df.columns[-1]].values
row_data_set = base_df[base_df.columns[:-1]].values
print(len(base_df))


600


In [4]:
discretizatior_base = discretizatior.sample(DIVIDE_NUM)
vectorised_discretizatior = np.frompyfunc(discretizatior_base, 1, 1)
discretizated_data_set = [vectorised_discretizatior(data) for data in row_data_set]
print(discretizated_data_set, row_data_set)


[array([1, 1], dtype=object), array([1, 1], dtype=object), array([1, 2], dtype=object), array([2, 2], dtype=object), array([1, 2], dtype=object), array([2, 1], dtype=object), array([1, 1], dtype=object), array([1, 1], dtype=object), array([2, 1], dtype=object), array([1, 1], dtype=object), array([2, 1], dtype=object), array([1, 2], dtype=object), array([1, 1], dtype=object), array([1, 2], dtype=object), array([1, 1], dtype=object), array([2, 1], dtype=object), array([1, 1], dtype=object), array([2, 1], dtype=object), array([1, 1], dtype=object), array([2, 1], dtype=object), array([1, 1], dtype=object), array([1, 1], dtype=object), array([1, 1], dtype=object), array([1, 1], dtype=object), array([1, 1], dtype=object), array([2, 2], dtype=object), array([1, 2], dtype=object), array([1, 2], dtype=object), array([1, 2], dtype=object), array([1, 1], dtype=object), array([1, 1], dtype=object), array([2, 1], dtype=object), array([2, 1], dtype=object), array([1, 1], dtype=object), array([1, 1],

# DataFrameのテスト

In [5]:
test_dh = dh.DataHolder(discretizated_data_set, class_set)
print(test_dh.extract_class(0).data_set, test_dh.extract_class(0).class_set)
print(test_dh.extract_class_and_index(0, 1, 0).data_set)
print("c", test_dh.count)
print(type(test_dh.count))


[array([1, 1], dtype=object) array([1, 1], dtype=object)
 array([1, 2], dtype=object) array([2, 2], dtype=object)
 array([1, 2], dtype=object) array([2, 1], dtype=object)
 array([1, 1], dtype=object) array([1, 1], dtype=object)
 array([2, 1], dtype=object) array([1, 1], dtype=object)
 array([2, 1], dtype=object) array([1, 2], dtype=object)
 array([1, 1], dtype=object) array([1, 2], dtype=object)
 array([1, 1], dtype=object) array([2, 1], dtype=object)
 array([1, 1], dtype=object) array([2, 1], dtype=object)
 array([1, 1], dtype=object) array([2, 1], dtype=object)
 array([1, 1], dtype=object) array([1, 1], dtype=object)
 array([1, 1], dtype=object) array([1, 1], dtype=object)
 array([1, 1], dtype=object) array([2, 2], dtype=object)
 array([1, 2], dtype=object) array([1, 2], dtype=object)
 array([1, 2], dtype=object) array([1, 1], dtype=object)
 array([1, 1], dtype=object) array([2, 1], dtype=object)
 array([2, 1], dtype=object) array([1, 1], dtype=object)
 array([1, 1], dtype=object) ar

In [6]:
print(test_dh.extract_data_index(0, 0).data_set)

[]


# 確率の箇所のテスト

In [7]:
test_pb = pc.ProbCalculator(test_dh)
print(test_pb.prob_class(0))
print(test_pb.prob_class(1))
print(test_pb.prob_class(2))
print(test_pb.prob_class(3))
print(test_pb.prob_data_index(0, 0))
print(test_pb.prob_data_index(0, 1))
print(test_pb.prob_data_index(0, 2))
print(test_pb.prob_data_index(0, 3))
print(test_pb.prob_data_index(0, 4))
print(test_pb.prob_data_index(0, 0)+test_pb.prob_data_index(0, 1)+test_pb.prob_data_index(0, 2)+test_pb.prob_data_index(0, 3)+test_pb.prob_data_index(0, 4))


0.25
0.25
0.25
0.25
0.0
0.36666666666666664
0.13333333333333333
0.1
0.4
1.0


In [19]:
print(test_pb.prob_data_index_and_class(0, 1, 0))
print(test_pb.prob_data_index_and_class(0, 1, 1))
print(test_pb.prob_data_index_and_class(0, 1, 2))
print(test_pb.prob_data_index_and_class(0, 1, 3))



0.175
0.19166666666666668
0.0
0.0


In [22]:
print(test_pb.prob_data_index_in_class(0, 1, 0))
print(test_pb.prob_data_index_in_class(0, 1, 1))
print(test_pb.prob_data_index_in_class(0, 1, 2))
print(test_pb.prob_data_index_in_class(0, 1, 3))


0.7
0.7666666666666667
0.0
0.0


In [10]:
print(test_pb.prob_data_index_in_class(0, 1, 0)*test_pb.prob_class(0))

0.175
